// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRyI_E9rDEPkgvJirwNaYOQev3ZXEfn5Q',
    appId: '1:747814975336:web:d1c286b9fa50ddd50c48dd',
    messagingSenderId: '747814975336',
    projectId: 'test-gsg-5a8e3',
    authDomain: 'test-gsg-5a8e3.firebaseapp.com',
    storageBucket: 'test-gsg-5a8e3.appspot.com',
    measurementId: 'G-QEGNTWQCSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsT--sjaK7F6Ta3lcHhzxUAKmUdzZt1B0',
    appId: '1:747814975336:android:511b50823734c9b70c48dd',
    messagingSenderId: '747814975336',
    projectId: 'test-gsg-5a8e3',
    storageBucket: 'test-gsg-5a8e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_SEcCA2uVCvsTEtoE9cGXQzNirPgj0w',
    appId: '1:747814975336:ios:2b6972f000542af60c48dd',
    messagingSenderId: '747814975336',
    projectId: 'test-gsg-5a8e3',
    storageBucket: 'test-gsg-5a8e3.appspot.com',
    iosClientId: '747814975336-askcmsbhsiphbiocqmquidu5gbt66ek9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_SEcCA2uVCvsTEtoE9cGXQzNirPgj0w',
    appId: '1:747814975336:ios:2b6972f000542af60c48dd',
    messagingSenderId: '747814975336',
    projectId: 'test-gsg-5a8e3',
    storageBucket: 'test-gsg-5a8e3.appspot.com',
    iosClientId: '747814975336-askcmsbhsiphbiocqmquidu5gbt66ek9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
